name: Test - Docker

on:
  workflow_dispatch: {}
  pull_request:
    types: [opened]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install Package
        run: |
          pip install -e .[all]
          pip install torch

      - name: Test
        run: |
          black --check .
          isort --diff .
          flake8 .
          pytest --docker tests/
          mypy unipipe/
